version: '3.8'

services:
  api-gateway:
    image: ${DOCKER_REGISTRY:-babbly}/babbly-api-gateway:${TAG:-latest}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    networks:
      - babbly-network

networks:
  babbly-network:
    external: true 