FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["babbly-api-gateway/babbly-api-gateway.csproj", "./"]
RUN dotnet restore "babbly-api-gateway.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "babbly-api-gateway/babbly-api-gateway.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "babbly-api-gateway/babbly-api-gateway.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_ENVIRONMENT=Development
ENV MOCK_SERVICES=true
ENTRYPOINT ["dotnet", "babbly-api-gateway.dll"] 