global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'babbly-api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'user-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'post-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['post-service:8080']

  - job_name: 'comment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['comment-service:8080']

  - job_name: 'like-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['like-service:8080'] 