apiVersion: batch/v1
kind: Job
metadata:
  name: simple-load-test
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: load-test
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting simple load test..."
          
          # Simple CPU-intensive load test
          for i in $(seq 1 5000); do
            curl -s http://api-gateway:5010/health > /dev/null &
            curl -s http://api-gateway:5010/metrics > /dev/null &
            
            # Generate some CPU load
            if [ $(( $i % 100 )) -eq 0 ]; then
              echo "Completed $i requests"
              sleep 0.1
            fi
          done
          
          wait
          echo "Simple load test completed"
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi" 
            cpu: "100m"
      restartPolicy: Never
  backoffLimit: 0 